# If you already have an entry for sensor here, just change "sensor: !include_dir_list integrations/sensors" to "sensor split: !include_dir_list integrations/sensors"
# This will tell homeassistant to load both without getting confused because of two "sensor:" entries. The same goes for "automation:"
sensor: !include_dir_list integrations/sensors

automation: !include_dir_list automations

shell_command: !include_dir_merge_named shell_commands/
